### ISSUE TITLE
Show RemotePhoto

### ISSUE THREAD

**Issue by Alexookah** [tungvoduc/DTPhotoViewerController#22]
It would be nice to show the FullScreen View with a loader and download the remote photo.

What do you think?
 great library by the way

**Comment by tungvoduc** [comment]
@Alexookah I am actually using my library to display remote photos and also add loader. In order to achieve that, you need to: 
- Subclass DTPhotoCollectionViewCell and add your own loader, this should be very easy. Then call this method on your photo viewer, better subclass and create your own photo viewer controller: 
```swift
func registerClassPhotoViewer(_ cellClass: Swift.AnyClass?)
```
- Implement this optional data source method,make loader spin if image has not been downloaded and stop loader if it has:

```swift
func photoViewerController(_ photoViewerController: DTPhotoViewerController, configureCell cell: DTPhotoCollectionViewCell, forPhotoAt index: Int)
```

**Comment by Alexookah** [comment]
so i can use any image downloader library with this implementation. nice will try it out.
thank you

**Comment by tungvoduc** [comment]
@Alexookah Yes, that's right. Good luck!

**Comment by Alexookah** [comment]
@tungvoduc 
Could you please provide a full example of your implementation if its possible?
